name 'treegraft'
maintainer 'David Marshall'
maintainer_email 'dmarshall@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures treegraft'
version '0.1.1'
chef_version '>= 15.0'

issues_url 'https://github.com/dwmarshall/treegraft/issues'
source_url 'https://github.com/dwmarshall/treegraft'
